apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - outline-service.yaml
  - outline-statefulset.yaml
  - outline-pdb.yaml
  - outline-pv.yaml
  - redis-service.yaml
  - redis-statefulset.yaml
  - redis-pv.yaml
