apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: netbox
  namespace: netbox
resources:
  - resources/httpproxy.yaml
helmCharts:
  - name: netbox
    version: 7.3.5
    repo: "oci://ghcr.io/netbox-community/netbox-chart/netbox"
    releaseName: "netbox"
    namespace: netbox
    valuesFile: "helm/values.yaml"
